// This is the main.js file. Import global CSS and scripts here.
// The Client API can be used here. Learn more: gridsome.org/docs/client-api

import DefaultLayout from '~/layouts/Default.vue'
import VueFormulate from '@braid/vue-formulate'
import { fr } from '@braid/vue-formulate-i18n'
import LogRocket from 'logrocket';
import { plugins } from '../gridsome.config';
import VueMatomo from 'vue-matomo';

LogRocket.init('xz8jmz/territoires-store');

export default function (Vue, { router, head, isClient }) {
  // Set default layout as a global component
  Vue.component('Layout', DefaultLayout)

  Vue.use(VueFormulate, {
    plugins: [ fr ],
    locale: 'fr',
    classes: {
      outer: 'mb-4',
      input: 'border border-gray-400 rounded px-3 py-2 leading-none focus:border-blue-500 outline-none border-box w-full mb-1',
      label: 'font-medium text-sm',
      help: 'text-xs mb-1 text-gray-600',
      error: 'text-red-700 text-xs mb-1'
    }
  })

  let ROOT_PATH = 'https://territoires.store'

  // Set Head
  head.htmlAttrs = { lang: 'fr' }
  const socialMediaMeta = [
    // Twitter Card
    // {key:'twitter:card', property: 'twitter:card', content: 'summary'},
    // {key:'twitter:title', property: 'twitter:title', content: `L'Incubateur des Territoires`},
    // {key:'twitter:description', property: 'twitter:description', content: `Une mission de l'Agence nationale de la cohesion des territoires`},
    // image must be an absolute path
    {key:'twitter:image', property: 'twitter:image', content: `${ROOT_PATH}/favicon.png`},
    // Facebook OpenGraph
    // {key:'og:title', property: 'og:title', content: `L'Incubateur des Territoires`},
    // {key:'og:site_name', property: 'og:site_name', content: `L'Incubateur des Territoires`},
    // {key:'og:type', property: 'og:type', content: 'website'},
    {key:'og:image', property: 'og:image', content: `${ROOT_PATH}/favicon.png`},
    // {key:'og:description', property: 'og:description', content: `Une mission de l'Agence nationale de la cohesion des territoires`}
  ]

  head.meta = head.meta.concat(socialMediaMeta)

  // Set Matomo
  Vue.use(VueMatomo, {
    // Configure your matomo server and site by providing
    host: 'https://stats.data.gouv.fr',
    siteId: 164,
  
    // Changes the default .js and .php endpoint's filename
    // Default: 'matomo'
    trackerFileName: 'matomo',
  
    // Overrides the autogenerated tracker endpoint entirely
    // Default: undefined
    // trackerUrl: 'https://example.com/whatever/endpoint/you/have',
  
    // Overrides the autogenerated tracker script path entirely
    // Default: undefined
    // trackerScriptUrl: 'https://example.com/whatever/script/path/you/have',
  
    // Enables automatically registering pageviews on the router
    router: router,
  
    // Enables link tracking on regular links. Note that this won't
    // work for routing links (ie. internal Vue router links)
    // Default: true
    enableLinkTracking: true,
  
    // Require consent before sending tracking information to matomo
    // Default: false
    requireConsent: false,
  
    // Whether to track the initial page view
    // Default: true
    trackInitialView: true,
  
    // Run Matomo without cookies
    // Default: false
    disableCookies: false,
  
    // Enable the heartbeat timer (https://developer.matomo.org/guides/tracking-javascript-guide#accurately-measure-the-time-spent-on-each-page)
    // Default: false
    enableHeartBeatTimer: false,
  
    // Set the heartbeat timer interval
    // Default: 15
    heartBeatTimerInterval: 15,
  
    // Whether or not to log debug information
    // Default: false
    debug: false,
  
    // UserID passed to Matomo (see https://developer.matomo.org/guides/tracking-javascript-guide#user-id)
    // Default: undefined
    userId: undefined,
  
    // Share the tracking cookie across subdomains (see https://developer.matomo.org/guides/tracking-javascript-guide#measuring-domains-andor-sub-domains)
    // Default: undefined, example '*.example.com'
    cookieDomain: undefined,
  
    // Tell Matomo the website domain so that clicks on these domains are not tracked as 'Outlinks'
    // Default: undefined, example: '*.example.com'
    domains: 'territoires.store',
  
    // A list of pre-initialization actions that run before matomo is loaded
    // Default: []
    // Example: [
    //   ['API_method_name', parameter_list],
    //   ['setCustomVariable','1','VisitorType','Member'],
    //   ['appendToTrackingUrl', 'new_visit=1'],
    //   etc.
    // ]
    preInitActions: []
  })
}
